apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: org-allowed-registries
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: org-registries
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Images may only come from ghcr.io or harbor2.zoller.com."
      pattern:
        spec:
          containers:
          - image: "ghcr.io/* | harbor2.zoller.com/*"
