apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image
  annotations:
    policies.kyverno.io/title: Verify Org Images
    policies.kyverno.io/category: My Org
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      For now, we only want to verify signatures for two image repos
      both coming from GHCR. This will change in the future.
spec:
  validationFailureAction: enforce
  rules:
    - name: check-signatures
      match:
        any:
        - resources:
            kinds:
              - Pod
      context:
      - name: keys
        configMap:
          name: keys
          namespace: default
      verifyImages:
      - imageReferences:
        - "ghcr.io/chipzoller/zulu*"
        - "ghcr.io/chipzoller/busybox*"
        required: true
        attestors:
        - count: 1
          entries:
          - keys: 
              publicKeys: "{{ keys.data.production }}"
